---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "book_service"
  name: "book-service-sv"
spec:
  ports:
  - name: "port-1-book-ser"
    port: 9090
    protocol: "TCP"
    targetPort: 9090
  selector:
    app: "book_service"
  type: "ClusterIP"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "book_service"
  name: "book-service-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "book_service"
  template:
    metadata:
      labels:
        app: "book_service"
    spec:
      containers:
      - image: "usman16/book_service:latest"
        lifecycle:
          preStop:
            exec:
              command:
              - "sleep"
              - "15"
        name: "book-service-deployment"
        ports:
        - containerPort: 9090
          name: "port-1-book-ser"
          protocol: "TCP"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "100Mi"
            cpu: "200m"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  labels:
    app: "book_service"
  name: "book-service-hp"
spec:
  maxReplicas: 2
  metrics:
  - resource:
      name: "cpu"
      target:
        averageUtilization: 50
        type: "Utilization"
    type: "Resource"
  minReplicas: 1
  scaleTargetRef:
    apiVersion: "apps/v1"
    kind: "Deployment"
    name: "book-service-deployment"
